export const products = [
  {
    name: "HP Gold",
    originalPrice: "299",
    discountedPrice: "199",
    quantity: "100",
    category: "Perfume",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=HP+Gold",
  },
  {
    name: "Hydrating Face Cream",
    originalPrice: "49",
    discountedPrice: "35",
    quantity: "150",
    category: "Skincare",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Face+Cream",
  },
  {
    name: "Anti-Acne Gel",
    originalPrice: "39",
    discountedPrice: "25",
    quantity: "100",
    category: "Skincare",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Anti+Acne+Gel",
  },
  {
    name: "Brightening Serum",
    originalPrice: "59",
    discountedPrice: "40",
    quantity: "120",
    category: "Skincare",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Serum",
  },
  {
    name: "Face Cleansing Foam",
    originalPrice: "35",
    discountedPrice: "25",
    quantity: "130",
    category: "Skincare",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Cleansing+Foam",
  },
  {
    name: "Night Repair Cream",
    originalPrice: "75",
    discountedPrice: "50",
    quantity: "110",
    category: "Skincare",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Night+Cream",
  },
  {
    name: "Volumizing Mascara",
    originalPrice: "29",
    discountedPrice: "19",
    quantity: "200",
    category: "Makeup",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Mascara",
  },
  {
    name: "Matte Lipstick Set",
    originalPrice: "39",
    discountedPrice: "25",
    quantity: "180",
    category: "Makeup",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Lipstick+Set",
  },
  {
    name: "Foundation with SPF",
    originalPrice: "45",
    discountedPrice: "30",
    quantity: "90",
    category: "Makeup",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Foundation",
  },
  {
    name: "Waterproof Eyeliner",
    originalPrice: "19",
    discountedPrice: "12",
    quantity: "250",
    category: "Makeup",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Eyeliner",
  },
  {
    name: "Blush Palette",
    originalPrice: "35",
    discountedPrice: "25",
    quantity: "140",
    category: "Makeup",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Blush+Palette",
  },
  {
    name: "Argan Oil Hair Serum",
    originalPrice: "59",
    discountedPrice: "40",
    quantity: "120",
    category: "Hair Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Hair+Serum",
  },
  {
    name: "Curl Defining Cream",
    originalPrice: "35",
    discountedPrice: "28",
    quantity: "130",
    category: "Hair Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Curl+Cream",
  },
  {
    name: "Anti-Dandruff Shampoo",
    originalPrice: "25",
    discountedPrice: "18",
    quantity: "150",
    category: "Hair Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Shampoo",
  },
  {
    name: "Leave-In Conditioner",
    originalPrice: "30",
    discountedPrice: "22",
    quantity: "200",
    category: "Hair Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Conditioner",
  },
  {
    name: "Heat Protection Spray",
    originalPrice: "20",
    discountedPrice: "15",
    quantity: "190",
    category: "Hair Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Heat+Spray",
  },
  {
    name: "Luxury Eau de Toilette",
    originalPrice: "129",
    discountedPrice: "89",
    quantity: "80",
    category: "Fragrance",
    image:
      "https://via.placeholder.com/150/000000/FFFFFF/?text=Eau+de+Toilette",
  },
  {
    name: "Citrus Fresh Cologne",
    originalPrice: "79",
    discountedPrice: "55",
    quantity: "100",
    category: "Fragrance",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Cologne",
  },
  {
    name: "Floral Mist Perfume",
    originalPrice: "99",
    discountedPrice: "70",
    quantity: "150",
    category: "Fragrance",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Mist+Perfume",
  },
  {
    name: "Woody Musk Perfume",
    originalPrice: "150",
    discountedPrice: "110",
    quantity: "90",
    category: "Fragrance",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Musk+Perfume",
  },
  {
    name: "Rose & Vanilla Perfume",
    originalPrice: "89",
    discountedPrice: "60",
    quantity: "110",
    category: "Fragrance",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Rose+Perfume",
  },
  {
    name: "Nourishing Nail Polish",
    originalPrice: "15",
    discountedPrice: "10",
    quantity: "300",
    category: "Nail Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Nail+Polish",
  },
  {
    name: "Quick Dry Top Coat",
    originalPrice: "12",
    discountedPrice: "8",
    quantity: "350",
    category: "Nail Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Top+Coat",
  },
  {
    name: "Cuticle Oil",
    originalPrice: "18",
    discountedPrice: "12",
    quantity: "280",
    category: "Nail Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Cuticle+Oil",
  },
  {
    name: "Nail Strengthener",
    originalPrice: "20",
    discountedPrice: "15",
    quantity: "240",
    category: "Nail Care",
    image:
      "https://via.placeholder.com/150/000000/FFFFFF/?text=Nail+Strengthener",
  },
  {
    name: "Glitter Nail Polish",
    originalPrice: "16",
    discountedPrice: "12",
    quantity: "220",
    category: "Nail Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Glitter+Polish",
  },
  {
    name: "Body Scrub & Lotion Set",
    originalPrice: "79",
    discountedPrice: "55",
    quantity: "90",
    category: "Body Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Body+Set",
  },
  {
    name: "Moisturizing Body Butter",
    originalPrice: "45",
    discountedPrice: "30",
    quantity: "150",
    category: "Body Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Body+Butter",
  },
  {
    name: "Aloe Vera Body Gel",
    originalPrice: "35",
    discountedPrice: "25",
    quantity: "100",
    category: "Body Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Body+Gel",
  },
  {
    name: "Firming Body Lotion",
    originalPrice: "60",
    discountedPrice: "40",
    quantity: "110",
    category: "Body Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Body+Lotion",
  },
  {
    name: "Lavender Body Oil",
    originalPrice: "50",
    discountedPrice: "35",
    quantity: "80",
    category: "Body Care",
    image: "https://via.placeholder.com/150/000000/FFFFFF/?text=Body+Oil",
  },
];
